package banyuwangi.digital.core.utils

object Constant {
    const val API_GET_WISATA = "wisata/get_wisata"
    const val API_GET_DETAIL_WISATA = "wisata/get_detail_wisata"
    const val API_GET_WISATA_RATING = "wisata/get_wisata_rating"
    const val API_GET_HOMESTAY = "homestay/get_homestay"
    const val API_GET_DETAIL_HOMESTAY = "homestay/get_detail_homestay"
    const val API_GET_AVAILABILITY_ROOMS = "homestay/get_availability_rooms"
    const val API_GET_TRAVEL_PACKAGE = "travel_package/get_travel_package"
    const val API_GET_DETAIL_TRAVEL_PACKAGE = "travel_package/get_detail_travel_package"
    const val API_GET_RESTAURANT = "restaurant/get_restaurant"
    const val API_GET_DETAIL_RESTAURANT = "restaurant/get_detail_restaurant"
    const val API_GET_NEWS = "news/get_news"
    const val API_INSERT_TRANSACTION_WISATA = "transaction_wisata/insert_transaction"
    const val API_GET_PAYMENT_METHOD = "payment_method/get_payment_method"
    const val API_GET_TRANSACTIONS = "transactions/get_transactions"
    const val API_GET_TRANSACTION_WISATA = "transaction_wisata/get_transaction_wisata"
    const val API_CHARGE_EWALLET = "payment/charge_ewallet"
    const val API_INSERT_TRANSACTION_HOMESTAY = "transaction_homestay/insert_transaction"
    const val API_GET_TRANSACTION_HOMESTAY = "transaction_homestay/get_transaction_homestay"
    const val API_GET_TRANSACTION_RESTAURANT = "transaction_restaurant/get_transaction_restaurant"
    const val API_UPDATE_EXPIRED_TRANSACTION = "transactions/update_expired_transaction"
    const val API_INSERT_TRANSACTION_TRAVEL_PACKAGE =
        "transaction_travel_package/insert_transaction"
    const val API_GET_TRANSACTION_TRAVEL_PACKAGE =
        "transaction_travel_package/get_transaction_travel_package"
    const val API_INSERT_TRANSACTION_RESTAURANT = "transaction_restaurant/insert_transaction"
    const val API_GET_MAPS_OUTLET = "maps/get_outlet"
    const val API_GET_TPSR_BALANCE = "tpsr/get_detail_tpsr"
    const val API_SEARCH = "search/search"
    const val API_GET_BANNER = "welcome/get_banner"
    const val API_DELETE_TICKET = "wisata/delete_ticket"
    const val API_ADD_TICKET = "wisata/add_ticket"
    const val API_EDIT_TICKET = "wisata/edit_ticket"
    const val API_DELETE_PHOTO = "wisata/delete_photo"
    const val API_ADD_PHOTO = "wisata/upload_photo"
}